# Generated by Django 6.0.3 on 2026-04-05 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('victims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OralHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='oral_histories/audio/')),
                ('transcript', models.TextField(blank=True)),
                ('interviewee_role', models.CharField(blank=True, help_text='e.g. Sister of victim, Community elder', max_length=255)),
                ('date_recorded', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('victim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oral_histories', to='victims.victim')),
            ],
            options={
                'verbose_name_plural': 'Oral histories',
                'ordering': ['-date_recorded'],
            },
        ),
    ]
