# Generated by Django 6.0.3 on 2026-04-06 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('victims', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('victim_name', models.CharField(blank=True, help_text='Leave blank if the name is unknown or withheld', max_length=255)),
                ('victim_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('victim_gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('NR', 'Not recorded')], max_length=2)),
                ('community_ward', models.CharField(max_length=255)),
                ('year_of_death', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cause_of_death', models.TextField(blank=True)),
                ('story', models.TextField(help_text='What you know about this person')),
                ('home_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('home_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('submitter_name', models.CharField(blank=True, max_length=255)),
                ('submitter_relationship', models.CharField(blank=True, help_text='e.g. Family member, Neighbour, Community leader', max_length=255)),
                ('submitter_contact', models.CharField(blank=True, help_text='Phone or email — only used for follow-up, never published', max_length=255)),
                ('submitter_consents', models.BooleanField(default=False, help_text='Submitter confirms they have authority to share this information')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('NEEDS_INFO', 'More Info Needed'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=15)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
                ('victim', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission', to='victims.victim')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
