# Generated by Django 6.0.3 on 2026-04-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=120, unique=True)),
                ('label', models.CharField(help_text='Human-readable name shown in the admin panel', max_length=200)),
                ('section', models.CharField(help_text='Grouping label e.g. hero, features, footer', max_length=60)),
                ('value', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['section', 'key'],
            },
        ),
    ]
