# Generated by Django 6.0.3 on 2026-04-05 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('age_at_death', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NR', 'Not Recorded')], default='NR', max_length=2)),
                ('community_ward', models.CharField(max_length=255)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('year_of_death', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cause_of_death', models.TextField(blank=True)),
                ('biographical_note', models.TextField(blank=True)),
                ('home_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('home_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('incident_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('incident_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('burial_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('burial_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('source', models.TextField(help_text='e.g. Church register, NGO report, family interview')),
                ('consent_status', models.CharField(choices=[('CONSENTED', 'Consented'), ('ANONYMOUS', 'Anonymous'), ('PENDING', 'Pending')], default='PENDING', max_length=10)),
                ('consent_date', models.DateField(blank=True, null=True)),
                ('consent_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='victims_added', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year_of_death', 'full_name'],
            },
        ),
    ]
